# Generated by Django 4.1.1 on 2022-10-08 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_name_category_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('image', models.ImageField(upload_to='images/brands/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренд',
            },
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Ключевые слова',
                'verbose_name_plural': 'Ключевые слова',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='images/products/<django.db.models.fields.CharField>/', verbose_name='Изображение товара')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображение товара',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер товара',
                'verbose_name_plural': 'Размер товара',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.BigIntegerField(default=0, verbose_name='Артикул')),
                ('material', models.CharField(max_length=120, verbose_name='Материал')),
                ('description', models.TextField(verbose_name='Описания товара')),
                ('characteristic', models.TextField(verbose_name='Характеристики товара')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category', verbose_name='Категория')),
                ('images', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productimage', verbose_name='Изображении товара')),
                ('sizes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productsize', verbose_name='Размеры')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
