# Generated by Django 4.1.1 on 2022-10-11 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_brand_keyword_productimage_productsize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='poster',
            field=models.ImageField(default='none', upload_to='images/products/posters/', verbose_name='Постер'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='images/products/<django.db.models.fields.related.ForeignKey>/', verbose_name='Изображение товара'),
        ),
    ]
