# Generated by Django 4.1.1 on 2022-10-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_images_remove_product_sizes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображения товаров', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'verbose_name': 'Размеры товаров', 'verbose_name_plural': 'Размеры товаров'},
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(to='product.category', verbose_name='Категория'),
        ),
    ]
