# Generated by Django 4.1.1 on 2022-10-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productimage_options_alter_productsize_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(max_length=120, null=True, verbose_name='Материал'),
        ),
    ]
