# Generated by Django 4.1.1 on 2022-10-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='images/products/images/', verbose_name='Изображение товара'),
        ),
    ]
