# Generated by Django 4.1.1 on 2022-10-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.ManyToManyField(to='product.keyword', verbose_name='Ключевые слова'),
        ),
    ]
