# Generated by Django 4.1.1 on 2022-11-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='isNew',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='product',
            name='isRecommended',
            field=models.BooleanField(default=False, verbose_name='Рекомендован'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(to='product.productsize', verbose_name='Размеры'),
        ),
    ]
